# Generated by Django 5.2.11 on 2026-02-21 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion_datos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=50)),
                ('libro_titulo', models.CharField(max_length=200, verbose_name='Libro')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_datos.colegio')),
            ],
            options={
                'verbose_name_plural': 'Asignaciones de Libros',
            },
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.CharField(max_length=50)),
                ('grado', models.CharField(max_length=50)),
                ('orden', models.IntegerField(default=0)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_datos.colegio')),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('materia', models.CharField(blank=True, max_length=100, null=True)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('bloque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cronograma.bloque')),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_datos.colegio')),
                ('profesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_datos.profesor')),
            ],
            options={
                'unique_together': {('fecha', 'bloque')},
            },
        ),
    ]
