# Generated by Django 5.2.11 on 2026-02-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cronograma', '0002_asignacion_fecha_fin_asignacion_fecha_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='¿Clase Cancelada?'),
        ),
        migrations.AddField(
            model_name='clase',
            name='comentarios',
            field=models.TextField(blank=True, null=True, verbose_name='Comentarios / Motivo'),
        ),
        migrations.AddField(
            model_name='clase',
            name='es_evento',
            field=models.BooleanField(default=False, verbose_name='¿Es un evento especial?'),
        ),
        migrations.AddField(
            model_name='clase',
            name='titulo_evento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título del Evento'),
        ),
    ]
